events {}

http {
    access_log /dev/stdout;
    error_log /dev/stderr info;

    server {
        listen 80;
        server_name _;
        root /var/www/html;
        index index.html index.php;

        client_max_body_size 128m;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~ \.php$ {
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTP_X_REAL_IP $remote_addr;
            fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
            fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
            fastcgi_pass app:9000;
        }
    }
}
